services:
  - type: web
    name: n8n
    env: docker
    region: Frankfurt # Render n'a pas de région à Abidjan, on garde une région disponible
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESQL_CONNECTION_URL
        value: postgresql://neondb_owner:npg_Zv8SrAW9CzTD@ep-solitary-frog-ada95tma-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: PORT
        value: 5678
      - key: N8N_LOG_LEVEL
        value: info
      - key: GENERIC_TIMEZONE
        value: Africa/Abidjan
      - key: TZ
        value: Africa/Abidjan
      - key: N8N_DEFAULT_LOCALE
        value: fr
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
